### ISSUE TITLE
[REQUEST] Silcon Labs Zigbee EmberZNet 6.10.9 NCP firmware image as stable release

### ISSUE THREAD

**Issue by Hedda** [xsp1989/zigbeeFirmware#47]
Please consider releasing firmware builds of Silcon Labs Zigbee EmberZNet 6.10.9.0 NCP firmware image as a "stable" release:

https://www.silabs.com/documents/public/release-notes/emberznet-release-notes-6.10.9.0.pdf

Silabs Zigbee EmberZNet 6.10.9.0 is a bug-fix release of 6.10 and contains a few important fixes for those who run older firmware.

Like to request you add EmberZNet 6.10.9.0 or later  Zigbee NCP firmware images (as an upgrade for existing 6.10.3.0 images).

That should keep all existing compatibility and could act as "stable" stop-gap while users experiment with 7.3.x+ series firmware.

Release notes PRF cover SDK version(s):
6.10.9.0 released October 25, 2023
6.10.8.0 released September 5, 2023
6.10.7.0 released July 13, 2023
6.10.5.0 released March 29, 2023
6.10.4.0 released January 11, 2023
6.10.3.0 released October 13, 2021
6.10.2.0 released September 8, 2021
6.10.1.0 released July 21, 2021
6.10.0.0 released June 16, 2021

### Fixed in release 6.10.9.0

?

### Fixed in release 6.10.8.0

?

### Fixed in release 6.10.7.0

ID # | Description
-- | --
398694, 823888, 519731 | ZCL reporting plugin is modified so that a rarely occurring exception condition (failure to read a reportable attribute's value; possibly because the attribute's endpoint is disabled) does not result in excess execution cycles, repetitive printing of a debug message, and (for an RTOS configuration) blocking of a lower-priority task.
841499 | Fixed issue where a newly joined device can sometimes not get added to the child table if its IEEE address is not known.
1150905 | Fixed spurious frame pending bit set when there is no data pending.

### Fixed in release 6.10.5.0

ID # | Description
-- | --
1103581 | Fixed an issue that caused a new device to join the network with a random extended PAN Id instead of using the same from received beacon. This difference in extended PAN Id was causing a PAN Id conflict upon device join.

**Comment by xsp1989** [comment]
I don't plan to release a new version. The last two versions have not made any feature updates or bug fixes, just because the platform code has been updated.
The following record comes from the SDK instructions：

EmberZNet SDK 6.10.9.0
requires Gecko Platform 3.2.9
What's new in the Zigbee EmberZNet SDK 6.10.9.0
* Underlying platform changes only

What's new in the Zigbee EmberZNet SDK 6.10.8.0
* Underlying platform changes only

What's new in the Zigbee EmberZNet SDK 6.10.7.0
* Support for EFR32xG21, Revision C and later, plus bug fixes

hat's new in the Zigbee EmberZNet SDK 6.10.5.0
* Selected quality improvements and bug fixes 

What's new in the Zigbee EmberZNet SDK 6.10.4.0 (Limited access)
* Early access part support

What's new in the Zigbee EmberZNet SDK 6.10.3.0
* Selected quality improvements and bug fixes

What's new in the Zigbee EmberZNet SDK 6.10.2.0
* Selected quality improvements and bug fixes

What's new in the Zigbee EmberZNet SDK 6.10.1.0
* Selected quality improvements and bug fixes

What's new in the Zigbee EmberZNet SDK 6.10.0.0
* Support for redesigned MG22 radio board (BRD4183C)
* Updated IAR and GCC compiler versions

The following record comes from the platform description：

Gecko Platform 3.2.9
What's new in Gecko Platform 3.2.9.0
* Support for EFR32xG22, Revision D

What's new in Gecko Platform 3.2.8.0
* Bootloader: One update

What's new in Gecko Platform 3.2.7.0
* Support for EFR32xG21, Revision C and later

What's new in Gecko Platform 3.2.5.0
* Early access part support

What's new in Gecko Platform 3.2.4.0 (Limited Access)
* Early access part support

What's new in Gecko Platform 3.2.3.0
* Selected quality improvements and bug fixes

What's new in Gecko Platform 3.2.2.0
* Introduced support for EFR32xG23 devices

What's new in Gecko Platform 3.2.1.0
* Selected quality improvements and bug fixes

What's new in Gecko Platform 3.2.0.0
* Peripherals
  * EFP Voltage scaling and Direct mode on EFR32xG22 and EFM32xG22
  * EFP Coulomb counter
* Services
  * Several fixes related to Power Manager
* Middleware
  * CSLIB can now be used with the Gecko SDK components
* Security
  * Mbed TLS library updated to v2.26.0
* Operating System
  * Added more NOR Flash options for Micrium OS FS
* Examples
  * Coulomb Counter
  * CLI & I2C
* Boards and External Devices
  * Added support for several new boards
* Other Platform Components
  * Updated IAR compiler to version 8.50.9.
  * Updated GCC compiler to version 10.2.
  * Amazon FreeRTOS Libraries have been added to the Gecko SDK.
